**DEF1**: A **vector** $\vec{n}$ of dimension $n$ is an ordered collection of $n$ elements, which supports

1. addition: 

$$
\vec{u} + \vec{v}
$$

2. scalar multiplication:

$$a\vec{v}$$

where $a$ belongs to a certain feild $F$.

**Axioms**:
$$
\begin{align*}
\vec{u} + (\vec{v} + \vec{w}) &= (\vec{u} + \vec{v}) + \vec{w} & \ldots\text{additive associativity} \\
\vec{v} + \vec{w} &= \vec{w} + \vec{v} & \dots\text{additive commutativity} \\
\exists \vec{0}. \forall \vec{v}. \ \vec{0} + \vec{v} &= \vec{v} & \ldots\text{additive identity} \\
\forall \vec{v}. \exists -\vec{v}. \vec{v} + (-\vec{v}) &= \vec{0} & \ldots\text{additive inverse}\\
a(b\vec{v}) &= (ab)\vec{v} & \ldots\text{multiplicative associativity}\\
1\vec{v} &= \vec{v} & \ldots\text{multiplicative identity} \\
a(\vec{v} + \vec{w}) &= a\vec{v} + a\vec{w} & \ldots\text{multiplicative distributivity} \\
(a + b)\vec{v} &= a\vec{v} + b\vec{v} & \ldots\text{field additive distributivity}
\end{align*}
$$

**DEF2**: A **linear combination** of $\vec{u}$ and $\vec{v}$ is:

$$
a\vec{u} + b\vec{v}
$$

**DEF3**: A **span** of a collection of vectors $\vec{i_1}, \vec{i_2}, ...$ is:
    
$$
\forall a. \forall b. a\vec{u} + b\vec{v}
$$

**DEF4**: $\vec{u}$ and $\vec{v}$ are **linear dependent** if:

$$
\exists a. a\vec{u} = \vec{v}
$$

*DEF4.1*: A set of vectors $\{\vec{v_1}, \vec{v_2}, \dots, \vec{v_n}\}$ is *linear independent* if:

$$
!\exists a_1 = a_2 = \dots = a_n = 0.\   a_1\vec{v_1} + a_2\vec{v_2} + \dots + a_n\vec{v_n} = \vec{0}
$$

**DEF5**: A **basis** $B$ is a set of *linear independent* vectors.

**DEF6**: A **linear transformation** $L$ is a function $\vec{u} \to \vec{v}$, such that preserve

1. addition

$$
L(\vec{v} + \vec{w}) = L(\vec{v}) + L(\vec{w})
$$

2. scalar multiplication

$$
L(c\vec{v}) = cL(\vec{v})
$$

The geometrical understanding of a linear transformation is by tracking the outcome of the basis. Linear means *keeping grid lines parallel and evenly spaced*.

$$
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
$$

The matrix above is to transfer the basis from $\{(1,0), (0,1)\}$ to $\{(a, c), (b, d)\}$.

To apply the transformation $F$ on a vector $(x, y)$, do:

$$
\begin{bmatrix} a & b \\ c & d \end{bmatrix}
\begin{bmatrix} x \\ y\end{bmatrix}
= x \begin{bmatrix} a \\ c\end{bmatrix} + y \begin{bmatrix} b \\ d\end{bmatrix}
= \begin{bmatrix} ax + by \\ cx + dy \end{bmatrix}
$$

**INF6.1**: linear transformation is **associative**
$$
A(BC) = (AB)C
$$

**INF6.2** linear transformation is **NOT commutative**
$$
AB \neq BA
$$

**DEF7**: the **determinant** of a matrix $M$ is

$$
\text{det}\left(
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
\right) = ad - bc
$$

**INF7.1**:
$$
\text{det}(MN) = \text{det}(M)\text{det}(N)
$$

**DEF8**: linear system of equations

$$
\begin{bmatrix}
2 & 5 & 3 \\
4 & 0 & 8 \\
1 & 3 & 0 \\
\end{bmatrix}
\begin{bmatrix} x \\ y \\ z \end{bmatrix} =
\begin{bmatrix} -3 \\ 0 \\ 2 \end{bmatrix}
$$

can be written as:
$$
A\vec{x} = \vec{v}
$$

**DEF9**: an inverse of $A$ is $A^{-1}$ such that

$$
A^{-1}A = I
$$

**INF9.0.1**:
$$
A^{-1}A = AA^{-1}
$$

**DEF9.1**: the solution of $\vec{x}$ is
$$
\vec{x} = A^{-1}\vec{v}
$$

**DEF9.2**:
$$
\forall A. \text{det}(A) \neq 0 \Rightarrow \exists A^{-1}
$$

**DEF10**: a **rank** of $A$ is the number of dimensions in its *column space*. $A$ is *full rank* if the rank is maximum.

**DEF11**: a **null space** or **kernel** of $A$ it's the space that all output vectors become *null*.

**DEF12**:

$$
\begin{bmatrix}
a \\ b
\end{bmatrix}
\cdot
\begin{bmatrix}
c \\ d
\end{bmatrix}
= ac + bd
$$

The *dual* of linear transformation $[a,b]$ is a vector $(a,b)$ in that space.

Dot product is to transfer a vector into a linear transformation.

The geomarical meaning is to project $\vec{u}$ onto $\vec{v}$ and compute the product of lengths.

**INF12.1**: commutativity
$$
\vec{v}\cdot\vec{w} = \vec{w}\cdot\vec{v}
$$

**DEF13**:
$$
\begin{bmatrix} a \\ b \end{bmatrix} \times \begin{bmatrix} c \\ d \end{bmatrix}
= \text{det}\left(
\begin{bmatrix}
a & c \\
b & d
\end{bmatrix}
\right)
$$

**DEF13.1**:
$$
\begin{bmatrix} a \\ b \\ c\end{bmatrix} \times \begin{bmatrix} d \\ e \\ f \end{bmatrix}
= \text{det}\left(
\begin{bmatrix}
\hat{i} & a & d \\
\hat{j} & b & e \\
\hat{k} & c & f
\end{bmatrix}
\right)
$$

**INF13.2**: orientation
$$
\vec{v}\times\vec{w} = -\vec{w}\times\vec{v}
$$

**INF13.3**: The dual of $f: \vec{x} \to \text{volume of parallelepiped}(\vec{x}, \vec{v}, \vec{w}))$ is a $\vec{p}$ such that:

$$
\begin{bmatrix}
p_1 \\ p_2 \\ p_3
\end{bmatrix}
\cdot
\begin{bmatrix}
x \\ y \\ z
\end{bmatrix}
=
\text{det}\left(
\begin{bmatrix}
x & v_1 & w_1 \\
y & v_2 & w_2 \\
z & v_3 & w_3
\end{bmatrix}
\right)
$$

**INF14**: Given a linear transformation $M$ with $I$ as the basis, and another basis $B$. The corresponding linear transformation in $B$'s coordinate system is:

$$
M_B = B^{-1}MB
$$

**DEF15**: **Eigenvectors** of a linear transformation $M$ are vectors where its input and output are linear dependent. **Eigenvalues** are the scaling ratio of ouput/input.

$$
A\vec{v} = \lambda \vec{v}
$$

**INF15.1**: solution
$$
\begin{align*}
A\vec{v} & = \lambda \vec{v} \\
A\vec{v} & = (\lambda I)\vec{v}\\
(A - \lambda I)\vec{v} & = \vec{0} \\
\text{det}(A - \lambda I) & = 0
\end{align*}
$$

**INF15.2**: The transformation $M$ in its *eigenbasis* $E$ is always *diagonal*

$$
\begin{bmatrix}
1 & -1 \\
0 & 1
\end{bmatrix}^{-1}
\begin{bmatrix}
3 & 1 \\
0 & 2
\end{bmatrix}
\begin{bmatrix}
1 & -1 \\
0 & 1
\end{bmatrix}
=
\begin{bmatrix}
3 & 0 \\
0 & 2
\end{bmatrix}
$$

where $[(3,0),(1,2)]$ is the transformation, $(1,0)$ and $(-1,1)$ are the eigenbasis.

**INF15.3**: compute $A^k$
$$
\begin{align*}
D & := S^{-1}AS \\
A & = SDS^{-1} \\
A^k & = (SDS^{-1})^k \\
    & = \underbrace{(SDS^{-1})(SDS^{-1})\ldots(SDS^{-1})}_{k} \\
    & = SD^kS^{-1}
\end{align*}
$$

where $S$ is the eigenbasis of $A$

**Q1**: Take the following matrix:
$$
A = \begin{bmatrix} 0 & 1 \\ 1 & 1 \end{bmatrix}
$$

Start computing its first few powers by hand: $A^2$, $A^3$, etc.

1. What pattern do you see?
2. Can you explain why this pattern shows up?

This might make you curious to know if there's an efficient way to compute arbitrary powers of this matrix. $A^n$ for any number $n$.

In [35]:
import numpy as np

A = np.matrix('0, 1; 1, 1')
I = np.matrix('1, 0; 0, 1')

print(A * A)
print(A * A * A)
print(A * A * A * A)

from numpy import linalg as LA

eig_vals, S = LA.eig(A)
print('eigen basis: {}'.format(S))

Si = S ** -1
D = Si * A * S
print('eigen trans: {}'.format(D))

def fib(n):
    return S * (D ** n) * Si

for i in range(2, 5):
    print(fib(i))

[[1 1]
 [1 2]]
[[1 2]
 [2 3]]
[[2 3]
 [3 5]]
eigen basis: [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
eigen trans: [[-6.18033989e-01  1.11022302e-16]
 [ 1.11022302e-16  1.61803399e+00]]
[[1. 1.]
 [1. 2.]]
[[1. 2.]
 [2. 3.]]
[[2. 3.]
 [3. 5.]]


**Q2**: Given that two eigenvectors of this matrix are
$$
\begin{align*}
\vec{v_1} = \begin{bmatrix} 2 \\ 1 + \sqrt{5} \end{bmatrix} & &
\vec{v_2} = \begin{bmatrix} 2 \\ 1 - \sqrt{5} \end{bmatrix}
\end{align*}
$$

see if you can figure out a way to compute $A^n$ by first chaning to an eigenbasis, compute the new representation of $A^n$ in that basis, then converting back to our standard basis. What does this formula tell you?

In [42]:
import numpy as np
from math import sqrt

A = np.matrix([
    [0, 1],
    [1, 1]
])

S = np.matrix([
    [2,           2],
    [1 + sqrt(5), 1 - sqrt(5)]
])
print('eigen basis: {}'.format(S))

Si = S ** -1

D = Si * A * S

def fib(n):
    return S * (D ** n) * Si

print(fib(5))

eigen basis: [[ 2.          2.        ]
 [ 3.23606798 -1.23606798]]
[[3. 5.]
 [5. 8.]]
